name: Deploy to GitHub Pages

on:
  # Trigger the workflow every time you push to the `main` branch
  # Using a different branch name? Replace `main` with your branch’s name
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4

      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Europe/Prague"

      - uses: actions/setup-node@v4

      - name: Install deps
        run: cd web && npm ci --force

      - name: Build web
        run: cd web && npm run build

      - name: Add custom domain
        run: 'touch web/build/CNAME && echo "c24ber.web3privacy.info" >> web/build/CNAME'

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./web/build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
